import { Resend } from 'resend';

let _resend: Resend | null = null;
function getResend(): Resend {
  if (!_resend) {
    _resend = new Resend(process.env.RESEND_API_KEY);
  }
  return _resend;
}

export interface EmailOptions {
  to: string[];
  subject: string;
  html: string;
  text?: string;
  attachments?: Array<{
    filename: string;
    content: Buffer;
    contentType?: string;
  }>;
}

/**
 * Send email via Resend with optional PDF attachments.
 * If report contains 🚨, subject gets [URGENT] prefix.
 */
export async function sendEmail(options: EmailOptions): Promise<void> {
  const from = process.env.EMAIL_FROM || 'agents@gaimchangergolf.com';

  const { data, error } = await getResend().emails.send({
    from,
    to: options.to,
    subject: options.subject,
    html: options.html,
    text: options.text,
    attachments: options.attachments?.map((a) => ({
      filename: a.filename,
      content: a.content,
    })),
  });

  if (error) {
    console.error('Email send error:', error);
    throw new Error(`Failed to send email: ${error.message}`);
  }

  console.log('Email sent:', data?.id);
}

/**
 * Get default recipient list from env.
 */
export function getDefaultRecipients(): string[] {
  const emailTo = process.env.EMAIL_TO || '';
  return emailTo.split(',').map((e) => e.trim()).filter(Boolean);
}

/**
 * Build an HTML email body for agent reports.
 */
export function buildReportEmail(
  agentName: string,
  agentTitle: string,
  reportContent: string,
  date: string
): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0a; color: #e5e5e5; padding: 20px; }
        .container { max-width: 700px; margin: 0 auto; }
        .header { border-bottom: 2px solid #2d8a4e; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { color: #2d8a4e; font-size: 24px; margin: 0; }
        .header p { color: #888; margin: 4px 0 0; }
        .meta { color: #888; font-size: 13px; margin-bottom: 20px; }
        .content { background: #141414; border: 1px solid #262626; border-radius: 8px; padding: 24px; line-height: 1.6; white-space: pre-wrap; }
        .footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #262626; color: #666; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>Gaimchanger Golf — Corporate HQ</h1>
          <p>${agentName} • ${agentTitle}</p>
        </div>
        <div class="meta">Report Date: ${date}</div>
        <div class="content">${reportContent}</div>
        <div class="footer">
          Generated by Gaimchanger Golf AI Agent Platform<br/>
          Powered by Anthropic Claude
        </div>
      </div>
    </body>
    </html>
  `;
}
