'use client';

import React, { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { MarketingPlan } from '@/lib/types';

const planStatusColors: Record<string, string> = {
  draft: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  approved: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  rejected: 'bg-neutral-700/30 text-neutral-400 border-neutral-700',
  'in-progress': 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  completed: 'bg-green-500/10 text-green-400 border-green-500/20',
};

const itemStatusColors: Record<string, string> = {
  pending: 'bg-neutral-800 text-neutral-400 border-neutral-700',
  generating: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  ready: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  scheduled: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  published: 'bg-green-500/10 text-green-400 border-green-500/20',
  error: 'bg-red-500/10 text-red-400 border-red-500/20',
};

export default function PlanDetailPage() {
  const params = useParams();
  const id = params.id as string;

  const [plan, setPlan] = useState<MarketingPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);

  const fetchPlan = useCallback(async () => {
    try {
      const res = await fetch(`/api/social/plans/${id}`);
      const data = await res.json();
      setPlan(data.plan || null);
    } catch (err) {
      console.error('Failed to fetch plan:', err);
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    fetchPlan();
  }, [fetchPlan]);

  const handleApprove = async () => {
    if (!confirm('Approve this plan? Predis will start generating content for every post.')) return;
    setBusy('approving');
    try {
      const res = await fetch(`/api/social/plans/${id}/approve`, { method: 'POST' });
      const data = await res.json();
      if (data.plan) setPlan(data.plan);
      else alert(data.error || 'Approve failed');
    } finally {
      setBusy(null);
    }
  };

  const handleReject = async () => {
    if (!confirm('Reject this plan? It can be re-generated by re-running Sloane.')) return;
    setBusy('rejecting');
    try {
      const res = await fetch(`/api/social/plans/${id}/reject`, { method: 'POST' });
      const data = await res.json();
      if (data.plan) setPlan(data.plan);
    } finally {
      setBusy(null);
    }
  };

  const handleSync = async () => {
    setBusy('syncing');
    try {
      const res = await fetch(`/api/social/plans/${id}/sync`, { method: 'POST' });
      const data = await res.json();
      if (data.plan) setPlan(data.plan);
    } finally {
      setBusy(null);
    }
  };

  if (loading) {
    return <div className="max-w-7xl mx-auto px-4 py-12 text-neutral-400">Loading…</div>;
  }

  if (!plan) {
    return (
      <div className="max-w-7xl mx-auto px-4 py-12">
        <h1 className="text-2xl font-bold text-white mb-4">Plan Not Found</h1>
        <Link href="/dashboard/social-media/plans" className="text-[#B5A36B]">
          Back to plans
        </Link>
      </div>
    );
  }

  const canApprove = plan.status === 'draft';

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <Link
        href="/dashboard/social-media/plans"
        className="text-sm text-[#B5A36B] hover:text-[#C9BA88] mb-4 inline-block"
      >
        ← All plans
      </Link>

      <div className="flex items-start justify-between gap-4 mb-8">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <h1 className="text-3xl font-bold text-white">Week of {plan.weekOf}</h1>
            <span
              className={`text-xs px-2 py-0.5 rounded-full border ${
                planStatusColors[plan.status] ||
                'bg-neutral-800 text-neutral-400 border-neutral-700'
              }`}
            >
              {plan.status}
            </span>
          </div>
          <p className="text-neutral-400">
            {plan.items.length} posts · created {new Date(plan.createdAt).toLocaleString()}
          </p>
        </div>

        <div className="flex gap-2">
          {canApprove && (
            <>
              <button
                onClick={handleApprove}
                disabled={busy !== null}
                className="px-4 py-2 bg-green-600 hover:bg-green-500 disabled:bg-neutral-700 text-white font-semibold rounded-lg transition-colors"
              >
                {busy === 'approving' ? 'Approving…' : 'Approve & send to Predis'}
              </button>
              <button
                onClick={handleReject}
                disabled={busy !== null}
                className="px-4 py-2 bg-neutral-800 hover:bg-neutral-700 disabled:bg-neutral-900 text-white font-semibold rounded-lg transition-colors"
              >
                {busy === 'rejecting' ? 'Rejecting…' : 'Reject'}
              </button>
            </>
          )}
          {plan.status === 'in-progress' && (
            <button
              onClick={handleSync}
              disabled={busy !== null}
              className="px-4 py-2 bg-[#B5A36B] hover:bg-[#C9BA88] disabled:bg-neutral-700 text-black font-semibold rounded-lg transition-colors"
            >
              {busy === 'syncing' ? 'Syncing…' : 'Sync from Predis'}
            </button>
          )}
        </div>
      </div>

      {plan.goals.length > 0 && (
        <section className="mb-8">
          <h2 className="text-lg font-semibold text-white mb-3">Goals</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {plan.goals.map((g, i) => (
              <div
                key={i}
                className="bg-neutral-900/50 border border-neutral-800 rounded-lg p-4"
              >
                <div className="text-xs text-neutral-500 uppercase tracking-wide">
                  {g.metric}
                </div>
                <div className="text-lg font-semibold text-white mt-1">{g.target}</div>
              </div>
            ))}
          </div>
        </section>
      )}

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-white mb-3">
          Posts ({plan.items.length})
        </h2>
        <div className="space-y-3">
          {plan.items.map((item) => (
            <div
              key={item.id}
              className="bg-neutral-900/50 border border-neutral-800 rounded-xl p-5"
            >
              <div className="flex items-start justify-between gap-4 mb-3">
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap mb-2">
                    <span className="text-sm font-mono text-[#B5A36B]">
                      {item.date} · {item.postTime}
                    </span>
                    <span className="text-xs px-2 py-0.5 rounded-full bg-neutral-800 text-neutral-300 border border-neutral-700">
                      {item.platform}
                    </span>
                    <span className="text-xs px-2 py-0.5 rounded-full bg-neutral-800 text-neutral-300 border border-neutral-700">
                      {item.format}
                    </span>
                    {item.predisStatus && (
                      <span
                        className={`text-xs px-2 py-0.5 rounded-full border ${
                          itemStatusColors[item.predisStatus] ||
                          'bg-neutral-800 text-neutral-400 border-neutral-700'
                        }`}
                      >
                        {item.predisStatus}
                      </span>
                    )}
                  </div>
                  <h3 className="font-semibold text-white">{item.theme}</h3>
                </div>
                {item.predisPreviewUrl && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={item.predisPreviewUrl}
                    alt="Predis preview"
                    className="w-20 h-20 object-cover rounded-lg shrink-0"
                  />
                )}
              </div>

              <div className="space-y-2 text-sm">
                <div>
                  <span className="text-neutral-500">Hook: </span>
                  <span className="text-neutral-200">{item.hook}</span>
                </div>
                <div>
                  <span className="text-neutral-500">Caption: </span>
                  <span className="text-neutral-200 whitespace-pre-wrap">
                    {item.caption}
                  </span>
                </div>
                <div>
                  <span className="text-neutral-500">Visual: </span>
                  <span className="text-neutral-200">{item.visualConcept}</span>
                </div>
                {item.hashtags.length > 0 && (
                  <div>
                    <span className="text-neutral-500">Hashtags: </span>
                    <span className="text-[#B5A36B]">{item.hashtags.join(' ')}</span>
                  </div>
                )}
                {item.predisError && (
                  <div className="text-red-400 text-xs mt-2 bg-red-500/5 border border-red-500/20 rounded p-2">
                    {item.predisError}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </section>

      <section>
        <details className="bg-neutral-900/50 border border-neutral-800 rounded-xl p-5">
          <summary className="cursor-pointer text-white font-semibold">
            Sloane&apos;s full report
          </summary>
          <pre className="mt-4 text-sm text-neutral-300 whitespace-pre-wrap font-mono">
            {plan.rawReport}
          </pre>
        </details>
      </section>
    </div>
  );
}
